### ISSUE TITLE
Article Composer

### ISSUE THREAD

**Issue by veselosky** [veselosky/bluebucket#12]
As a Blue Bucket user
I want a web form where I can enter Article information
So that I can easily post content to my web site without learning JSON.

### Features
- The SAVE button will save your changes to the Drafts folder.
- The SAVE & CLOSE button will save your changes to the Drafts folder, and load the Site Organizer.
- The PUBLISH button will save your changes to the Archetypes folder, removing it from Drafts.
- A text box is provided to enter article text. Type markdown. (A Lambda function will convert it to HTML after saving. Lambda function is a separate Feature, not part of this Feature).
- Metadata is entered in the sidebar form.
    * Title is required.
    * Author will be pre-populated from the site config (site.author).
    * Publish date will be pre-populated with NOW.
    * Item type and GUID will be auto-generated and are not editable.

### Constraints
- This version will have no WYSIWYG or writing tools. You get a text box. Write markdown. The system will convert it to HTML on save.

### Tasks
- [ ] Build the Article Composer form, with validation
- [ ] Implement the SAVE and SAVE & CLOSE buttons
- [ ] Implement the PUBLISH button

![bb composer](https://cloud.githubusercontent.com/assets/103601/14769874/8e60b55c-0a30-11e6-9d0c-397ba973c19f.png)
