### ISSUE TITLE
Document Account Bootstrapping, Bucket Initialization

### ISSUE THREAD

**Issue by veselosky** [veselosky/bluebucket#17]
As a Power User or Developer of Blue Bucket
I want a document that explains simply how files and tasks interact in the system
So that I have the knowledge I need to troubleshoot problems and make improvements.

**Branch:** docflows

### Tasks

- [x] Workflow diagram showing installation in new AWS account
- [x] Prose description of installation in new AWS account; requirements.
- [x] Workflow diagram showing initialization of new bucket 
- [x] Prose description of initialization of new bucket ; requirements.
- [x] Workflow diagram showing software update of existing AWS account
- [x] Prose description of software update of existing AWS account; requirements
