### ISSUE TITLE
Document File Flows and Task Flows

### ISSUE THREAD

**Issue by veselosky** [veselosky/bluebucket#5]
As a Power User or Developer of Blue Bucket
I want a document that explains simply how files and tasks interact in the system
So that I have the knowledge I need to troubleshoot problems and make improvements.

**Branch:** docflows

### Tasks
- [x] Workflow diagram showing end-to-end publishing
- [X] Prose description of directory structures, with rationale
- [X] Prose descriptions of artifact types and their roles in the system
